### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by petrklus**
Examples updated to make them work

### CODE REVIEW

**Comment by meteozond** [comment]
Wow, thanks @petrklus!

**Comment by petrklus** [comment]
Thank you for your work! Are you using the module in some of your projects?
I am interested in using it with database-backed backend (to enable
versioning etc.)

**Comment by meteozond** [comment]
Yep, we are using it as one of file management APIs for our CDN.
Not sure that got your idea about versioned database-backed backend, but ready to answer any your question if get some.

**Comment by petrklus** [comment]
Great stuff! Effectively, I would like to present users with a WebDav share
they can mount using for example CyberDuck to edit HTML files. However,
instead of editing files directly on the FS, all of the data would be
actually served from the database, and the database objects will be
versioned. So if a user wants to go back in time, they can login to admin
console and roll-back any changes they made...

**Pull request merged**
